### ISSUE TITLE
Epic | Dark/light theme

### ISSUE THREAD

**Issue by rthanga1** [trimble-oss/modus-mobile-maui-components#40]
Based on theme control styling should be changed.

- [x] Initial setup of dark and light theme
- [x] POC for applying styles.
- [ ] Apply the styling for all controls.
- [x] Check the possibility for custom theme

**Comment by Sofiya-kumar** [comment]
- Added the initial setup files for light and dark themes to support both modes.
- Custom theme also supports.
- Applied theme setup for button control.
